import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin Authnetication",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body>
      <div className="flex h-screen bg-gray-100">{children}</div>
    </body>
  );
}
