import type { Metadata } from "next";
import Sidebar from "./_components/sidebar";
import Header from "./_components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <div className="flex h-screen bg-gray-100">
          <div>
            <Sidebar />
          </div>
          <div className="flex-1">
            <div>
              <Header />
            </div>

            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
